twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme: ['forms/materialize_form_template.html.twig']
    paths:
        public/: public
    globals:
        categories: '@App\Service\Categories\CategoriesManagement'