#!/usr/bin/env bash

COMMANDE=$1
LISTE_COMMANDES=(reset list)

if [ "$COMMANDE" = "reset" ]; then
    php bin/console doctrine:database:drop --force
    php bin/console doctrine:database:create
    rm -rf ./src/Migrations/**/*.php
    php bin/console make:migration
    php bin/console doctrine:migrations:migrate
fi

if [ "$COMMANDE" = "list" ]; then
    for c in ${LISTE_COMMANDES[@]}; do
        echo "$c"
    done
fi