webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'

    # preload all rendered script and link tags automatically via the http2 Link header
    preload: true

    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    strict_mode: true
